//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34011
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteWebQuidditch.ServiceReferenceQuidditch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCoupe", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SCoupe : SiteWebQuidditch.ServiceReferenceQuidditch.SEntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SEntityObject", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SPersonne))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SJoueur))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SSpectateur))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SStade))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SMatch))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe))]
    public partial class SEntityObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SEquipe", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SEquipe : SiteWebQuidditch.ServiceReferenceQuidditch.SEntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPersonne", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SJoueur))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SiteWebQuidditch.ServiceReferenceQuidditch.SSpectateur))]
    public partial class SPersonne : SiteWebQuidditch.ServiceReferenceQuidditch.SEntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SJoueur", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SJoueur : SiteWebQuidditch.ServiceReferenceQuidditch.SPersonne {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSpectateur", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SSpectateur : SiteWebQuidditch.ServiceReferenceQuidditch.SPersonne {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SStade", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SStade : SiteWebQuidditch.ServiceReferenceQuidditch.SEntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMatch", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SMatch : SiteWebQuidditch.ServiceReferenceQuidditch.SEntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SUtilisateur", Namespace="http://schemas.datacontract.org/2004/07/QuidditchService")]
    [System.SerializableAttribute()]
    public partial class SUtilisateur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQuidditch.IServiceQuidditch")]
    public interface IServiceQuidditch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/CreateUser", ReplyAction="http://tempuri.org/IServiceQuidditch/CreateUserResponse")]
        void CreateUser(string inLogin, string inPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/CreateUser", ReplyAction="http://tempuri.org/IServiceQuidditch/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string inLogin, string inPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllCoupes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllCoupesResponse")]
        SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe[] GetAllCoupes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllCoupes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllCoupesResponse")]
        System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe[]> GetAllCoupesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllEquipes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllEquipesResponse")]
        SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe[] GetAllEquipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllEquipes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllEquipesResponse")]
        System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe[]> GetAllEquipesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipe", ReplyAction="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipeResponse")]
        SiteWebQuidditch.ServiceReferenceQuidditch.SJoueur[] GetJoueursOfEquipe(SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe inEquipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipe", ReplyAction="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipeResponse")]
        System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SJoueur[]> GetJoueursOfEquipeAsync(SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe inEquipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllStades", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllStadesResponse")]
        SiteWebQuidditch.ServiceReferenceQuidditch.SStade[] GetAllStades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllStades", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllStadesResponse")]
        System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SStade[]> GetAllStadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetMatchsOfCoupe", ReplyAction="http://tempuri.org/IServiceQuidditch/GetMatchsOfCoupeResponse")]
        SiteWebQuidditch.ServiceReferenceQuidditch.SMatch[] GetMatchsOfCoupe(SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe inCoupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetMatchsOfCoupe", ReplyAction="http://tempuri.org/IServiceQuidditch/GetMatchsOfCoupeResponse")]
        System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SMatch[]> GetMatchsOfCoupeAsync(SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe inCoupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetUtilisateur", ReplyAction="http://tempuri.org/IServiceQuidditch/GetUtilisateurResponse")]
        SiteWebQuidditch.ServiceReferenceQuidditch.SUtilisateur GetUtilisateur(string inLogin, string inPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetUtilisateur", ReplyAction="http://tempuri.org/IServiceQuidditch/GetUtilisateurResponse")]
        System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SUtilisateur> GetUtilisateurAsync(string inLogin, string inPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/ReserverPlaces", ReplyAction="http://tempuri.org/IServiceQuidditch/ReserverPlacesResponse")]
        int ReserverPlaces(SiteWebQuidditch.ServiceReferenceQuidditch.SMatch inMatch, int inNbPlaces, SiteWebQuidditch.ServiceReferenceQuidditch.SSpectateur inSpect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/ReserverPlaces", ReplyAction="http://tempuri.org/IServiceQuidditch/ReserverPlacesResponse")]
        System.Threading.Tasks.Task<int> ReserverPlacesAsync(SiteWebQuidditch.ServiceReferenceQuidditch.SMatch inMatch, int inNbPlaces, SiteWebQuidditch.ServiceReferenceQuidditch.SSpectateur inSpect);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceQuidditchChannel : SiteWebQuidditch.ServiceReferenceQuidditch.IServiceQuidditch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceQuidditchClient : System.ServiceModel.ClientBase<SiteWebQuidditch.ServiceReferenceQuidditch.IServiceQuidditch>, SiteWebQuidditch.ServiceReferenceQuidditch.IServiceQuidditch {
        
        public ServiceQuidditchClient() {
        }
        
        public ServiceQuidditchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceQuidditchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuidditchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuidditchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateUser(string inLogin, string inPasswd) {
            base.Channel.CreateUser(inLogin, inPasswd);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string inLogin, string inPasswd) {
            return base.Channel.CreateUserAsync(inLogin, inPasswd);
        }
        
        public SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe[] GetAllCoupes() {
            return base.Channel.GetAllCoupes();
        }
        
        public System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe[]> GetAllCoupesAsync() {
            return base.Channel.GetAllCoupesAsync();
        }
        
        public SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe[] GetAllEquipes() {
            return base.Channel.GetAllEquipes();
        }
        
        public System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe[]> GetAllEquipesAsync() {
            return base.Channel.GetAllEquipesAsync();
        }
        
        public SiteWebQuidditch.ServiceReferenceQuidditch.SJoueur[] GetJoueursOfEquipe(SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe inEquipe) {
            return base.Channel.GetJoueursOfEquipe(inEquipe);
        }
        
        public System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SJoueur[]> GetJoueursOfEquipeAsync(SiteWebQuidditch.ServiceReferenceQuidditch.SEquipe inEquipe) {
            return base.Channel.GetJoueursOfEquipeAsync(inEquipe);
        }
        
        public SiteWebQuidditch.ServiceReferenceQuidditch.SStade[] GetAllStades() {
            return base.Channel.GetAllStades();
        }
        
        public System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SStade[]> GetAllStadesAsync() {
            return base.Channel.GetAllStadesAsync();
        }
        
        public SiteWebQuidditch.ServiceReferenceQuidditch.SMatch[] GetMatchsOfCoupe(SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe inCoupe) {
            return base.Channel.GetMatchsOfCoupe(inCoupe);
        }
        
        public System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SMatch[]> GetMatchsOfCoupeAsync(SiteWebQuidditch.ServiceReferenceQuidditch.SCoupe inCoupe) {
            return base.Channel.GetMatchsOfCoupeAsync(inCoupe);
        }
        
        public SiteWebQuidditch.ServiceReferenceQuidditch.SUtilisateur GetUtilisateur(string inLogin, string inPassword) {
            return base.Channel.GetUtilisateur(inLogin, inPassword);
        }
        
        public System.Threading.Tasks.Task<SiteWebQuidditch.ServiceReferenceQuidditch.SUtilisateur> GetUtilisateurAsync(string inLogin, string inPassword) {
            return base.Channel.GetUtilisateurAsync(inLogin, inPassword);
        }
        
        public int ReserverPlaces(SiteWebQuidditch.ServiceReferenceQuidditch.SMatch inMatch, int inNbPlaces, SiteWebQuidditch.ServiceReferenceQuidditch.SSpectateur inSpect) {
            return base.Channel.ReserverPlaces(inMatch, inNbPlaces, inSpect);
        }
        
        public System.Threading.Tasks.Task<int> ReserverPlacesAsync(SiteWebQuidditch.ServiceReferenceQuidditch.SMatch inMatch, int inNbPlaces, SiteWebQuidditch.ServiceReferenceQuidditch.SSpectateur inSpect) {
            return base.Channel.ReserverPlacesAsync(inMatch, inNbPlaces, inSpect);
        }
    }
}
