//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34011
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsUnitairesService.cs.ServiceReferenceQuidditch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQuidditch.IServiceQuidditch")]
    public interface IServiceQuidditch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/CreateUser", ReplyAction="http://tempuri.org/IServiceQuidditch/CreateUserResponse")]
        void CreateUser(string inLogin, string inPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/CreateUser", ReplyAction="http://tempuri.org/IServiceQuidditch/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(string inLogin, string inPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllCoupes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllCoupesResponse")]
        QuidditchService.SCoupe[] GetAllCoupes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllCoupes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllCoupesResponse")]
        System.Threading.Tasks.Task<QuidditchService.SCoupe[]> GetAllCoupesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllEquipes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllEquipesResponse")]
        QuidditchService.SEquipe[] GetAllEquipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllEquipes", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllEquipesResponse")]
        System.Threading.Tasks.Task<QuidditchService.SEquipe[]> GetAllEquipesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipe", ReplyAction="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipeResponse")]
        QuidditchService.SJoueur[] GetJoueursOfEquipe(QuidditchService.SEquipe inEquipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipe", ReplyAction="http://tempuri.org/IServiceQuidditch/GetJoueursOfEquipeResponse")]
        System.Threading.Tasks.Task<QuidditchService.SJoueur[]> GetJoueursOfEquipeAsync(QuidditchService.SEquipe inEquipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllStades", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllStadesResponse")]
        QuidditchService.SStade[] GetAllStades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuidditch/GetAllStades", ReplyAction="http://tempuri.org/IServiceQuidditch/GetAllStadesResponse")]
        System.Threading.Tasks.Task<QuidditchService.SStade[]> GetAllStadesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceQuidditchChannel : TestsUnitairesService.cs.ServiceReferenceQuidditch.IServiceQuidditch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceQuidditchClient : System.ServiceModel.ClientBase<TestsUnitairesService.cs.ServiceReferenceQuidditch.IServiceQuidditch>, TestsUnitairesService.cs.ServiceReferenceQuidditch.IServiceQuidditch {
        
        public ServiceQuidditchClient() {
        }
        
        public ServiceQuidditchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceQuidditchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuidditchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuidditchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateUser(string inLogin, string inPasswd) {
            base.Channel.CreateUser(inLogin, inPasswd);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string inLogin, string inPasswd) {
            return base.Channel.CreateUserAsync(inLogin, inPasswd);
        }
        
        public QuidditchService.SCoupe[] GetAllCoupes() {
            return base.Channel.GetAllCoupes();
        }
        
        public System.Threading.Tasks.Task<QuidditchService.SCoupe[]> GetAllCoupesAsync() {
            return base.Channel.GetAllCoupesAsync();
        }
        
        public QuidditchService.SEquipe[] GetAllEquipes() {
            return base.Channel.GetAllEquipes();
        }
        
        public System.Threading.Tasks.Task<QuidditchService.SEquipe[]> GetAllEquipesAsync() {
            return base.Channel.GetAllEquipesAsync();
        }
        
        public QuidditchService.SJoueur[] GetJoueursOfEquipe(QuidditchService.SEquipe inEquipe) {
            return base.Channel.GetJoueursOfEquipe(inEquipe);
        }
        
        public System.Threading.Tasks.Task<QuidditchService.SJoueur[]> GetJoueursOfEquipeAsync(QuidditchService.SEquipe inEquipe) {
            return base.Channel.GetJoueursOfEquipeAsync(inEquipe);
        }
        
        public QuidditchService.SStade[] GetAllStades() {
            return base.Channel.GetAllStades();
        }
        
        public System.Threading.Tasks.Task<QuidditchService.SStade[]> GetAllStadesAsync() {
            return base.Channel.GetAllStadesAsync();
        }
    }
}
